/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // myAutogeneratedSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.',
  //   }
  // ],

  // But you can create a sidebar manually
  // 关联 docusaurus.config.js 文件中的 sidebarId
  "Html+Css": [
    'FrontEnd/intro',
    {
      type: 'category',
      label: '01.HTML + CSS 学习',
      collapsible: true,
      collapsed: false,
      items:
        [
          'FrontEnd/Html+Css/html结构&标签',
        ]
    }
  ],

  C: [
    'intro',
    {
      type: 'category',
      // 关联 docusaurus.config.js 文件中的 label
      label: '01.C 语言学习',
      items: [
        'GameDev/C/intro'
      ],
    }
  ],


};

module.exports = sidebars;
