/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // myAutogeneratedSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.',
  //   }
  // ],

  // But you can create a sidebar manually
  // 关联 docusaurus.config.js 文件中的 sidebarId

  // HTML + CSS 笔记
  "Html+Css": [
    {
      type: 'category',
      label: '01.HTML + CSS 学习',
      link: {
        type: 'doc',
        id: 'FrontEnd/FrontEnd-guides',
      },
      collapsible: true,
      collapsed: false,
      items:
        [
          'FrontEnd/Html+Css/FrontEnd-Struct_Label',
          'FrontEnd/Html+Css/FrontEnd-List_Selector_Box',
          'FrontEnd/Html+Css/FrontEnd-Table_Text_Font_Element',
          'FrontEnd/Html+Css/FrontEnd-DefaultCss_Selector_Display_Background',
          'FrontEnd/Html+Css/FrontEnd-CSS_Feature',
          'FrontEnd/Html+Css/FrontEnd-Position_Index',
          'FrontEnd/Html+Css/FrontEnd-Display',
          'FrontEnd/Html+Css/FrontEnd-Case_XiaoMi',
          'FrontEnd/Html+Css/FrontEnd-CSS3'
        ]
    }
  ],

  // C 语言 笔记
  C: [
    {
      type: 'category',
      // 关联 docusaurus.config.js 文件中的 label
      label: '01.C 语言学习',
      link: {
        type: 'doc',
        id: 'GameDev/C/C-guides',
      },
      collapsible: true,
      collapsed: false,
      items: [
        'GameDev/C/C-Total_Learning',
        'GameDev/C/C-If_For',
        'GameDev/C/C-Function',
        'GameDev/C/C-Array',
        'GameDev/C/C-Operator',
        'GameDev/C/C-Pointer',
        'GameDev/C/C-Struct',
        'GameDev/C/C-Debug_skills',
        'GameDev/C/C-Array_Save',
        'GameDev/C/C-Pointer_Detail'
      ],
    }
  ],

  // C++ 语言 笔记
  "C++": [
    {
      type: 'category',
      // 关联 docusaurus.config.js 文件中的 label
      label: '02.C++ 学习',
      link: {
        type: 'doc',
        id: 'GameDev/C++/C++-guides',
      },
      collapsible: true,
      collapsed: false,
      items: [
        'GameDev/C++/C++-Game_Development',
        'GameDev/C++/C++-Basic_Language',
        'GameDev/C++/C++-Project_Contact'
      ],
    }
  ],

  // Docusaurus 主题制作笔记
  BlogTheme: [
    {
      type: 'category',
      // 关联 docusaurus.config.js 文件中的 label
      label: 'Docusaurus 主题制作',
      link: {
        type: 'doc',
        id: 'BlogTheme/docusaurus-guides',
      },
      items: [
        'BlogTheme/docusaurus-Writing_Guides',
        'BlogTheme/docusaurus-config'
      ],
    }
  ]

};

module.exports = sidebars;
